### ISSUE TITLE
Change the sample chart design

### ISSUE THREAD

**Issue by AndressaStefany** [AndressaStefany/severityPrediction#10]
In document `src\llm\baseline_results.ipynb`, we currently have this:
![eclipse_auc](https://github.com/AndressaStefany/severityPrediction/assets/12596216/d8117633-4108-4a8a-bb44-29d7155d3289)

And I want it to have this design (we can include the vertical lines if it'll be good):
![output](https://github.com/AndressaStefany/severityPrediction/assets/12596216/30d79937-3da9-4bb5-a60e-fccbf5af81c0)

The code can be seen at `src\explore\section_dataset.ipynb`.

**Note: Also remove the image title.**
**Note 2: Export with dpi 300 or in eps.**

**Comment by Rob174** [comment]
after discussion done
Results are pushed on main under data/baseline_studies (imgs and plots), notebook updated to be more modular (dependng of the dataset)

@AndressaStefany All good? If so you can close the issue

**Comment by Rob174** [comment]
b2de1a638075b422188726d8a8056863445fb3a1
