### ISSUE TITLE
Graph of confusion matrices

### ISSUE THREAD

**Issue by AndressaStefany** [AndressaStefany/severityPrediction#11]
What we have at the moment:

![confusion_matrixeclipse_72k_Test](https://github.com/AndressaStefany/severityPrediction/assets/12596216/c2cd2dff-7b62-4848-b73c-5e4ce2387aa1)

What I need:
- [x] Without title
- [x] More visible colors. For example: green on blue is not visible. Feel free to change the `cmap` of the graphics if you feel necessary
- [x] If feasible, remove the percentage complement, that is, leave only the percentage in green (precision, recall and accuracy)
- [x] If feasible, change `sum_col` and `sum_lin`

**Comment by Rob174** [comment]
"If feasible, change sum_col and sum_lin"
Change to which text or empty?

**Comment by Rob174** [comment]
"Without title": pass qrgument title with ""

**Comment by Rob174** [comment]
note: package of confusion matrix visibly has never been planned for non squared matrices
